import Head from "next/head"
import React from "react"
import PostCard from "../components/Postcard"

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {posts.map((post) => (
          <PostCard post={post} key={post.id} />
        ))}
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`http://localhost/nextpress/wordpress/graphql`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify({
      query: `
        query {
          posts {
            nodes {
              id
              title
              excerpt
              uri
              content
            }
          }
        }
      `,
    }),
  })
  const postData = await res.json()

  const posts = postData?.data?.posts?.nodes

  // Pass data to the page via props
  return { props: { posts } }
}
